# Generated by Django 5.1.7 on 2025-03-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientesdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido_paterno', models.TextField(blank=True, null=True)),
                ('apellido_materno', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rut', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('estado_civil', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('comuna', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(choices=[('PROGRAMADA', 'Programada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('raza', models.TextField(blank=True, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado_mascota', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('especie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.TextField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', null=True)),
                ('metodo_pago', models.TextField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], null=True)),
                ('clientesdos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='snippets.clientesdos')),
                ('consultas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='snippets.consultas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('cirugias', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='snippets.mascotas')),
            ],
        ),
        migrations.AddField(
            model_name='consultas',
            name='mascotas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.mascotas'),
        ),
        migrations.AddField(
            model_name='clientesdos',
            name='id_mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='snippets.mascotas'),
        ),
        migrations.CreateModel(
            name='Veterinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido_paterno', models.TextField(blank=True, null=True)),
                ('apellido_materno', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rut', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('estado_civil', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('comuna', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('num_colegiado', models.TextField(blank=True, null=True)),
                ('mascotas', models.ManyToManyField(blank=True, through='snippets.Consultas', to='snippets.mascotas')),
            ],
        ),
        migrations.AddField(
            model_name='consultas',
            name='veterinariosid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.veterinarios'),
        ),
    ]
