# Generated by Django 5.1.7 on 2025-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Consultas',
        ),
        migrations.RenameModel(
            old_name='Diagnostico',
            new_name='Diagnosticos',
        ),
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='ConsultaId',
            new_name='ConsultasId',
        ),
    ]
