# Generated by Django 5.1.7 on 2025-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_veterinarios_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarios',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
