# Generated by Django 5.1.7 on 2025-03-28 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_veterinarios_highlighted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='veterinariosid',
            new_name='veterinario',
        ),
        migrations.AddField(
            model_name='consultas',
            name='clientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.clientesdos'),
            preserve_default=False,
        ),
    ]
