# Generated by Django 5.1.7 on 2025-04-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_rename_veterinariosid_consultas_veterinario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='estado_mascota',
        ),
        migrations.AddField(
            model_name='facturas',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturas',
            name='total_deuda',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='consultas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='snippets.consultas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturas',
            name='estado_pago',
            field=models.TextField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', editable=False),
        ),
    ]
