# Generated by Django 5.1.7 on 2025-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_clientesdos_total_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesdos',
            name='total_deuda',
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
