# Generated by Django 5.1.7 on 2025-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_clientesdos_total_deuda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarios',
            name='highlighted',
        ),
    ]
