clientes_arr = [
    {
        "nombre": "Laura",
        "apellido_paterno": "Sánchez",
        "apellido_materno": "Muñoz",
        "fecha_nacimiento": "1988-04-12",
        "rut": "18.456.789-0",
        "telefono": "912345678",
        "email": "laura.sanchez@example.com",
        "sexo": "Femenino",
        "estado_civil": "Casada",
        "direccion": "Av. Providencia 1234",
        "ciudad": "Santiago",
        "comuna": "Providencia",
        "id_mascota": 3,
    },
    {
        "nombre": "Carlos",
        "apellido_paterno": "Fernández",
        "apellido_materno": "Rojas",
        "fecha_nacimiento": "1990-07-21",
        "rut": "16.789.234-1",
        "telefono": "987654321",
        "email": "carlos.fernandez@example.com",
        "sexo": "Masculino",
        "estado_civil": "Soltero",
        "direccion": "Calle Las Dalias 77",
        "ciudad": "Valparaíso",
        "comuna": "Viña del Mar",
        "id_mascota": 4,
    },
    {
        "nombre": "María José",
        "apellido_paterno": "González",
        "apellido_materno": "Araya",
        "fecha_nacimiento": "1985-09-15",
        "rut": "13.456.789-9",
        "telefono": "922334455",
        "email": "mj.gonzalez@example.com",
        "sexo": "Femenino",
        "estado_civil": "Soltera",
        "direccion": "Pje. Los Castaños 98",
        "ciudad": "Concepción",
        "comuna": "San Pedro de la Paz",
        "id_mascota": 5,
    },
    {
        "nombre": "Diego",
        "apellido_paterno": "Pérez",
        "apellido_materno": "Navarro",
        "fecha_nacimiento": "1995-03-30",
        "rut": "19.987.654-3",
        "telefono": "955667788",
        "email": "diego.perez@example.com",
        "sexo": "Masculino",
        "estado_civil": "Divorciado",
        "direccion": "Av. Alemania 456",
        "ciudad": "Temuco",
        "comuna": "Temuco Centro",
        "id_mascota": 6,
    },
    {
        "nombre": "Camila",
        "apellido_paterno": "Ruiz",
        "apellido_materno": "Salas",
        "fecha_nacimiento": "1992-12-01",
        "rut": "17.234.567-2",
        "telefono": "999887766",
        "email": "camila.ruiz@example.com",
        "sexo": "Femenino",
        "estado_civil": "Conviviente",
        "direccion": "Villa El Bosque 123",
        "ciudad": "Rancagua",
        "comuna": "Machalí",
        "id_mascota": 7,
    },
    {
        "nombre": "Felipe",
        "apellido_paterno": "Castillo",
        "apellido_materno": "Morales",
        "fecha_nacimiento": "1980-01-10",
        "rut": "11.234.567-4",
        "telefono": "966778899",
        "email": "felipe.castillo@example.com",
        "sexo": "Masculino",
        "estado_civil": "Casado",
        "direccion": "Camino El Alba 1420",
        "ciudad": "La Serena",
        "comuna": "La Florida",
        "id_mascota": 8,
    }
]
veterinarios_arr = [
    {
        "nombre": "Andrea",
        "apellido_paterno": "Ramírez",
        "apellido_materno": "Soto",
        "fecha_nacimiento": "1985-03-22",
        "rut": "12.345.678-9",
        "telefono": "987654321",
        "email": "andrea.ramirez@vetclinic.com",
        "sexo": "Femenino",
        "estado_civil": "Soltera",
        "direccion": "Calle Miraflores 101",
        "ciudad": "Santiago",
        "comuna": "Ñuñoa",
        "especialidad": "Medicina interna",
        "num_colegiado": "VET12345",
    },
    {
        "nombre": "Javier",
        "apellido_paterno": "López",
        "apellido_materno": "Carrasco",
        "fecha_nacimiento": "1979-06-10",
        "rut": "11.987.654-3",
        "telefono": "912345678",
        "email": "javier.lopez@vetclinic.com",
        "sexo": "Masculino",
        "estado_civil": "Casado",
        "direccion": "Av. Kennedy 2050",
        "ciudad": "Santiago",
        "comuna": "Vitacura",
        "especialidad": "Cirugía",
        "num_colegiado": "VET54321",
    },
    {
        "nombre": "Paula",
        "apellido_paterno": "Mora",
        "apellido_materno": "Alarcón",
        "fecha_nacimiento": "1990-11-02",
        "rut": "18.234.567-2",
        "telefono": "933445566",
        "email": "paula.mora@vetclinic.com",
        "sexo": "Femenino",
        "estado_civil": "Conviviente",
        "direccion": "Pje. La Esperanza 47",
        "ciudad": "Valparaíso",
        "comuna": "Playa Ancha",
        "especialidad": "Dermatología",
        "num_colegiado": "VET67584",
    },
    {
        "nombre": "Rodrigo",
        "apellido_paterno": "Fuentes",
        "apellido_materno": "Navarro",
        "fecha_nacimiento": "1988-01-18",
        "rut": "15.987.321-1",
        "telefono": "955667788",
        "email": "rodrigo.fuentes@vetclinic.com",
        "sexo": "Masculino",
        "estado_civil": "Casado",
        "direccion": "Camino El Mar 950",
        "ciudad": "La Serena",
        "comuna": "Coquimbo",
        "especialidad": "Oftalmología",
        "num_colegiado": "VET44556",
    },
    {
        "nombre": "Natalia",
        "apellido_paterno": "Pérez",
        "apellido_materno": "Contreras",
        "fecha_nacimiento": "1993-09-30",
        "rut": "17.888.999-5",
        "telefono": "944223311",
        "email": "natalia.perez@vetclinic.com",
        "sexo": "Femenino",
        "estado_civil": "Soltera",
        "direccion": "Av. Libertad 300",
        "ciudad": "Rancagua",
        "comuna": "Rancagua Centro",
        "especialidad": "Cardiología",
        "num_colegiado": "VET99887",
    },
    {
        "nombre": "Cristóbal",
        "apellido_paterno": "Silva",
        "apellido_materno": "Moreno",
        "fecha_nacimiento": "1982-07-05",
        "rut": "13.445.667-3",
        "telefono": "922334455",
        "email": "cristobal.silva@vetclinic.com",
        "sexo": "Masculino",
        "estado_civil": "Divorciado",
        "direccion": "Los Arrayanes 654",
        "ciudad": "Puerto Montt",
        "comuna": "Mirasol",
        "especialidad": "Oncología",
        "num_colegiado": "VET33221",
    }
]
# consultas_arr = [
#     {
#         "fecha_cita": "2025-04-15T10:00:00",
#         "motivo": "Vacunación anual",
#         "tratamiento": "Aplicación vacuna triple felina",
#         "diagnostico": "Sin novedades",
#         "observaciones": "Paciente tranquilo, sin signos clínicos relevantes.",
#         "veterinario": 1,
#         "clientes": 1,
#         "estado": "COMPLETADA",
#         "mascotas": 3
#     },
#     {
#         "fecha_cita": "2025-04-18T16:30:00",
#         "motivo": "Revisión por cojera",
#         "tratamiento": "Analgésico oral por 5 días",
#         "diagnostico": "Esguince leve en extremidad posterior",
#         "observaciones": "Revisar en 1 semana si persiste molestia.",
#         "veterinario": 2,
#         "clientes": 2,
#         "estado": "COMPLETADA",
#         "mascotas": 4
#     },
#     {
#         "fecha_cita": "2025-04-20T11:15:00",
#         "motivo": "Control posoperatorio",
#         "tratamiento": "Revisión de herida quirúrgica",
#         "diagnostico": "Recuperación favorable",
#         "observaciones": "Retiro de puntos programado para el 25 de abril.",
#         "veterinario": 3,
#         "clientes": 3,
#         "estado": "EN_PROGRESO",
#         "mascotas": 5
#     },
#     {
#         "fecha_cita": "2025-04-22T09:00:00",
#         "motivo": "Consulta dermatológica",
#         "tratamiento": "Shampoo medicado e inhibidor antihistamínico",
#         "diagnostico": "Dermatitis alérgica",
#         "observaciones": "Indicado control en 10 días.",
#         "veterinario": 4,
#         "clientes": 4,
#         "estado": "PROGRAMADA",
#         "mascotas": 6
#     },
#     {
#         "fecha_cita": "2025-04-25T14:00:00",
#         "motivo": "Desparasitación interna y externa",
#         "tratamiento": "Antiparasitario oral + pipeta",
#         "diagnostico": "Sin hallazgos relevantes",
#         "observaciones": "Repetir tratamiento en 3 meses.",
#         "veterinario": 5,
#         "clientes": 5,
#         "estado": "PROGRAMADA",
#         "mascotas": 7
#     },
#     {
#         "fecha_cita": "2025-04-26T13:45:00",
#         "motivo": "Consulta por letargo y vómitos",
#         "tratamiento": "Fluidoterapia + antibiótico inyectable",
#         "diagnostico": "Gastroenteritis aguda",
#         "observaciones": "Indicado control en 48 horas.",
#         "veterinario": 6,
#         "clientes": 6,
#         "estado": "PROGRAMADA",
#         "mascotas": 8
#     }
# ]
# facturas_arr = [
#     {
#         "monto_total": 35000.00,
#         "monto_pagado": 35000.00,
#         "estado_pago": "PAGADO",
#         "metodo_pago": "EFECTIVO",
#         "consultas": 1,
#         "clientesdos": 1,
#         "total_deuda": 0.00
#     },
#     {
#         "monto_total": 42000.00,
#         "monto_pagado": 20000.00,
#         "estado_pago": "PARCIAL",
#         "metodo_pago": "TRANSFERENCIA",
#         "consultas": 2,
#         "clientesdos": 2,
#         "total_deuda": 22000.00
#     },
#     {
#         "monto_total": 55000.00,
#         "monto_pagado": 0.00,
#         "estado_pago": "PENDIENTE",
#         "metodo_pago": None,
#         "consultas": 3,
#         "clientesdos": 3,
#         "total_deuda": 55000.00
#     },
#     {
#         "monto_total": 30000.00,
#         "monto_pagado": 15000.00,
#         "estado_pago": "PARCIAL",
#         "metodo_pago": "TARJETA",
#         "consultas": 4,
#         "clientesdos": 4,
#         "total_deuda": 15000.00
#     },
#     {
#         "monto_total": 27000.00,
#         "monto_pagado": 27000.00,
#         "estado_pago": "PAGADO",
#         "metodo_pago": "TARJETA",
#         "consultas": 5,
#         "clientesdos": 5,
#         "total_deuda": 0.00
#     },
#     {
#         "monto_total": 60000.00,
#         "monto_pagado": 0.00,
#         "estado_pago": "PENDIENTE",
#         "metodo_pago": None,
#         "consultas": 6,
#         "clientesdos": 6,
#         "total_deuda": 60000.00
#     }
# ]
# historial_arr = [
#     {
#         "mascota": 3,
#         "enfermedades_cronicas": "Insuficiencia renal crónica",
#         "alergias": "Alergia al pollo",
#         "cirugias": "Esterilización (2021)",
#         "antecedentes": "Historial de vómitos recurrentes tratados con dieta especializada."
#     },
#     {
#         "mascota": 4,
#         "enfermedades_cronicas": None,
#         "alergias": "Ninguna conocida",
#         "cirugias": "Extracción de cuerpo extraño (2022)",
#         "antecedentes": "Presentó un episodio de obstrucción intestinal."
#     },
#     {
#         "mascota": 5,
#         "enfermedades_cronicas": "Diabetes mellitus",
#         "alergias": "Alergia a pulgas",
#         "cirugias": "Ninguna",
#         "antecedentes": "Requiere insulina dos veces al día."
#     },
#     {
#         "mascota": 6,
#         "enfermedades_cronicas": None,
#         "alergias": "Alergia al shampoo convencional",
#         "cirugias": "Cirugía dental (2023)",
#         "antecedentes": "Profilaxis dental anual recomendada."
#     },
#     {
#         "mascota": 7,
#         "enfermedades_cronicas": "Artrosis",
#         "alergias": None,
#         "cirugias": "Artroscopía (2020)",
#         "antecedentes": "Necesita suplemento articular diario."
#     },
#     {
#         "mascota": 8,
#         "enfermedades_cronicas": None,
#         "alergias": None,
#         "cirugias": None,
#         "antecedentes": "Paciente joven, sin antecedentes médicos relevantes."
#     }
# ]
# mascotas_arr = [
#     {
#         "nombre": "Luna",
#         "fecha_nacimiento": "2019-03-15",
#         "especie": "Perro",
#         "raza": "Labrador Retriever",
#         "sexo": "Hembra",
#         "edad": 6,
#         "peso": 28.5
#     },
#     {
#         "nombre": "Simba",
#         "fecha_nacimiento": "2020-07-22",
#         "especie": "Gato",
#         "raza": "Maine Coon",
#         "sexo": "Macho",
#         "edad": 4,
#         "peso": 7.8
#     },
#     {
#         "nombre": "Coco",
#         "fecha_nacimiento": "2017-11-09",
#         "especie": "Perro",
#         "raza": "Poodle",
#         "sexo": "Macho",
#         "edad": 7,
#         "peso": 10.2
#     },
#     {
#         "nombre": "Nina",
#         "fecha_nacimiento": "2021-05-30",
#         "especie": "Gato",
#         "raza": "Siames",
#         "sexo": "Hembra",
#         "edad": 3,
#         "peso": 4.5
#     },
#     {
#         "nombre": "Rocky",
#         "fecha_nacimiento": "2018-02-01",
#         "especie": "Perro",
#         "raza": "Bulldog Francés",
#         "sexo": "Macho",
#         "edad": 6,
#         "peso": 13.7
#     },
#     {
#         "nombre": "Milo",
#         "fecha_nacimiento": "2022-10-10",
#         "especie": "Gato",
#         "raza": "Europeo",
#         "sexo": "Macho",
#         "edad": 2,
#         "peso": 5.3
#     }
# ]
